name: driver_task
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  ## StateManagement
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  feature_structure: ^1.0.4

  ## Network
  dio: ^5.9.0
  equatable: ^2.0.8

  ## UI
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.2
  flutter_svg: ^2.2.3
  flutter_staggered_animations: ^1.1.1

  
  ## Error handling
  either_dart: ^1.0.0

  ## Localization
  flutter_localizations:
    sdk: flutter
  intl: any
  easy_localization: ^3.0.8

  ## Env
  flutter_dotenv: ^6.0.0

  ## Router
  go_router: ^17.0.1

  ## Map
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_polyline_algorithm: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/translations/
    - assets/jsons/
    - assets/icons/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
